let masini = [
  {
    brand: "Mercedes-Benz",
    model: "CL-Class",
    putere: 89,
    locuri: 6,
    portiere: 5,
  },
  {
    brand: "Ford",
    model: "LTD Crown Victoria",
    putere: 267,
    locuri: 3,
    portiere: 5,
  },
  {
    brand: "Saab",
    model: "9000",
    putere: 149,
    locuri: 2,
    portiere: 6,
  },
  {
    brand: "Suzuki",
    model: "Grand Vitara",
    putere: 75,
    locuri: 3,
    portiere: 2,
  },
  {
    brand: "Kia",
    model: "Spectra",
    putere: 500,
    locuri: 1,
    portiere: 4,
  },
  {
    brand: "Chevrolet",
    model: "Express",
    putere: 455,
    locuri: 1,
    portiere: 5,
  },
  {
    brand: "Ford",
    model: "Explorer Sport Trac",
    putere: 83,
    locuri: 4,
    portiere: 1,
  },
  {
    brand: "Nissan",
    model: "Sentra",
    putere: 34,
    locuri: 2,
    portiere: 4,
  },
  {
    brand: "GMC",
    model: "Savana",
    putere: 360,
    locuri: 6,
    portiere: 2,
  },
  {
    brand: "GMC",
    model: "Sierra 2500",
    putere: 67,
    locuri: 3,
    portiere: 3,
  },
];
